spring:
  application:
    name: config-server-vault
  profiles:
    active: vault,native
#  config:
#    import: vault://
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/ISTAD/config-server-vault/
          add-label-locations: false
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: TOKEN
          token: myroot
          kv-version: 2
          backend: secret

#    vault:
#      authentication: token
#      token: myroot
#      host: localhost
#      port: 8200
#      scheme: http

